### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by csabagyarmati**
Support Carthage dependency manager.

### CODE REVIEW

**Comment by nerdycat** [comment]
Many thanks.

**Comment by nerdycat** [comment]
I have merged your pull request. 
But when I'am trying out with Carthage, it says "Dependency "Cupcake" has no shared framework schemes". Why does this happen?

**Comment by csabagyarmati** [comment]
Sorry for my late answer.
It's because when carthage checkout your repository the Cupcake.xcodeproj not appear, so carthage didn't find the shared scheme from this xcodeproj.
If I use it from my fork it's working seamlessly.
Maybe it's because your last tagged version is 1.2.1 and that tag doesn't contain the Cupcake.xcodeproj.
Try to create a new tag from the current master branch.

**Comment by csabagyarmati** [comment]
If you specify the master branch in the Cartfile it's working.
`github "nerdycat/Cupcake" "master"`

So it's because if  you don't specify the branch or version, carthage cloning the last tagged version (your 1.2.1) which doesn't contain the Cupcake.xcodeproj.
Create a new tagged version from the current master branch and it will be good.

**Comment by nerdycat** [comment]
Fixed that, thanks.

**Pull request merged**
